#!/usr/bin/env node
/**
 * generate_prover_toml.js — Convert merkle_data.json demo section into Prover.toml
 */

import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const merklePath = join(ROOT, "merkle", "merkle_data.json");
const outPath = join(ROOT, "circuits", "compliance", "Prover.toml");

const data = JSON.parse(readFileSync(merklePath, "utf8"));
const d = data.demo;
const ex = d.exclusion;
const jp = d.jurisdiction_proof;

function arrField(name, values) {
  return `${name} = [${values.map((v) => `"${v}"`).join(", ")}]`;
}

function arrU1(name, values) {
  return `${name} = [${values.join(", ")}]`;
}

const toml = `# Auto-generated by scripts/generate_prover_toml.js — do not edit manually
# Regenerate via: ./scripts/generate_proof.sh

# Public inputs
merkle_root = "${data.sanctions.root}"
min_threshold = "${d.min_threshold}"
max_threshold = "${d.max_threshold}"
allowed_jurisdictions_root = "${data.jurisdictions.root}"
nullifier = "${d.nullifier}"

# Private inputs
sender_address_hash = "${d.sender_address_hash}"
amount = "${d.amount}"
jurisdiction_code = "${d.jurisdiction_code}"
secret = "${d.secret}"
nonce = "${d.nonce}"

# Sanctions exclusion witnesses
left_neighbor = "${ex.left_neighbor}"
right_neighbor = "${ex.right_neighbor}"
${arrField("left_siblings", ex.left_siblings)}
${arrU1("left_indices", ex.left_indices)}
${arrField("right_siblings", ex.right_siblings)}
${arrU1("right_indices", ex.right_indices)}

# Jurisdiction membership
${arrField("jurisdiction_siblings", jp.siblings)}
${arrU1("jurisdiction_indices", jp.indices)}
`;

writeFileSync(outPath, toml);
console.log(`Wrote ${outPath}`);
